import type { AnalyzerResult, Finding } from '@codedoctor/shared';
import {
  createFinding,
  findDevelopmentMarker,
  hasAny,
  hasExtension,
  hasFile,
  hasPrefix,
  isGeneratedPath,
  isProductionSourcePath,
  lineInfo,
  type BrowserProject
} from './browserProject.js';

export function nodeAnalyzer(project: BrowserProject): AnalyzerResult {
  const findings: Finding[] = [];
  const packageFile = project.byPath['package.json'];
  if (!packageFile) {
    return { analyzerId: 'node-dependency', findings, skipped: true, skipReason: 'Not a Node project.' };
  }

  let packageJson: { scripts?: Record<string, string> } = {};
  try {
    packageJson = JSON.parse(packageFile.content) as { scripts?: Record<string, string> };
  } catch {
    findings.push(createFinding({
      title: 'Invalid package.json',
      description: 'package.json could not be parsed.',
      severity: 'high',
      category: 'config',
      filePath: 'package.json',
      evidence: ['JSON parsing failed.'],
      recommendation: 'Fix package.json syntax.',
      sourceAnalyzer: 'node-dependency',
      ruleId: 'node/invalid-package-json',
      confidence: 0.95
    }));
    return { analyzerId: 'node-dependency', findings };
  }

  const scripts = packageJson.scripts ?? {};
  for (const [name, command] of Object.entries(scripts)) {
    const match = command.match(/\b(?:node|tsx|ts-node)\s+([^\s]+)/);
    const target = match?.[1]?.replace(/^\.\//, '');
    if (target && !hasFile(project, target)) {
      findings.push(createFinding({
        title: 'Package script target is missing',
        description: 'A package.json script points to a file that does not exist.',
        severity: 'high',
        category: 'build',
        filePath: 'package.json',
        evidence: [`scripts.${name} runs "${command}", but ${target} was not found.`],
        recommendation: 'Create the referenced entry file or update the script to match the real entry point.',
        sourceAnalyzer: 'node-dependency',
        ruleId: 'node/script-target-missing',
        confidence: 0.95
      }));
    }
  }
  if (!hasAny(project, ['pnpm-lock.yaml', 'package-lock.json', 'yarn.lock'])) {
    findings.push(createFinding({
      title: 'Missing Node lockfile',
      description: 'The project has package.json but no package manager lockfile.',
      severity: 'medium',
      category: 'dependency',
      filePath: 'package.json',
      evidence: ['No pnpm-lock.yaml, package-lock.json, or yarn.lock found.'],
      recommendation: 'Commit the lockfile generated by the package manager used for the project.',
      sourceAnalyzer: 'node-dependency',
      ruleId: 'node/missing-lockfile',
      confidence: 0.86
    }));
  }
  if (!hasFile(project, '.env.example')) {
    findings.push(createFinding({
      title: 'Missing .env.example',
      description: 'The project does not document required environment variables.',
      severity: 'low',
      category: 'config',
      evidence: ['No .env.example file found.'],
      recommendation: 'Add .env.example with required variable names and safe placeholder values.',
      sourceAnalyzer: 'node-dependency',
      ruleId: 'node/env-example-missing',
      confidence: 0.55
    }));
  }
  return { analyzerId: 'node-dependency', findings };
}
export function pythonAnalyzer(project: BrowserProject): AnalyzerResult {
  const pythonFiles = project.files.filter((file) => file.path.endsWith('.py'));
  const hasPythonSignal = pythonFiles.length > 0 || hasAny(project, ['pyproject.toml', 'requirements.txt', 'Pipfile', 'poetry.lock', 'uv.lock']);
  if (!hasPythonSignal) {
    return { analyzerId: 'python-project', findings: [], skipped: true, skipReason: 'Not a Python project.' };
  }

  const findings: Finding[] = [];
  if (!hasAny(project, ['pyproject.toml', 'requirements.txt', 'Pipfile'])) {
    findings.push(createFinding({
      title: 'Python dependency manifest is missing',
      description: 'Python source exists, but no pyproject.toml, requirements.txt, or Pipfile was found.',
      severity: 'medium',
      category: 'dependency',
      evidence: ['No standard Python dependency manifest found at the project root.'],
      recommendation: 'Add pyproject.toml or requirements.txt so runtime dependencies are reproducible.',
      sourceAnalyzer: 'python-project',
      ruleId: 'python/dependency-manifest-missing',
      confidence: 0.84,
      applicableProjectTypes: ['python'],
      tags: ['python', 'dependency']
    }));
  }
  if (hasAny(project, ['pyproject.toml', 'Pipfile']) && !hasAny(project, ['uv.lock', 'poetry.lock', 'Pipfile.lock', 'requirements.lock'])) {
    findings.push(createFinding({
      title: 'Python lockfile is missing',
      description: 'The project uses a modern Python dependency manifest but has no lockfile.',
      severity: 'low',
      category: 'dependency',
      evidence: ['Found pyproject.toml or Pipfile without uv.lock, poetry.lock, or Pipfile.lock.'],
      recommendation: 'Commit the lockfile generated by uv, Poetry, or Pipenv when reproducible installs matter.',
      sourceAnalyzer: 'python-project',
      ruleId: 'python/lockfile-missing',
      confidence: 0.72,
      applicableProjectTypes: ['python'],
      tags: ['python', 'dependency']
    }));
  }
  const hasTests = project.files.some((file) => /^tests?\//.test(file.path) || /(^|\/)test_.*\.py$/.test(file.path) || /_test\.py$/.test(file.path));
  if (pythonFiles.length > 0 && !hasTests) {
    findings.push(createFinding({
      title: 'Python tests are not visible',
      description: 'No pytest/unittest-style test files or tests directory were found.',
      severity: 'medium',
      category: 'test',
      evidence: ['No tests/, test_*.py, or *_test.py files found.'],
      recommendation: 'Add a small tests/ suite and document the test command.',
      sourceAnalyzer: 'python-project',
      ruleId: 'python/test-signal-missing',
      confidence: 0.78,
      applicableProjectTypes: ['python'],
      tags: ['python', 'test']
    }));
  }
  for (const file of pythonFiles) {
    const broadExcept = file.content.match(/except\s+(Exception|BaseException)?\s*:\s*(pass)?/m);
    if (broadExcept?.index !== undefined) {
      const info = lineInfo(file.content, broadExcept.index);
      findings.push(createFinding({
        title: 'Broad or empty Python exception handling',
        description: 'A broad except block can hide runtime failures and make debugging harder.',
        severity: broadExcept[2] ? 'high' : 'medium',
        category: 'bug',
        filePath: file.path,
        startLine: info.line,
        endLine: info.line,
        codeSnippet: info.snippet,
        evidence: ['Matched a broad except block.'],
        recommendation: 'Catch a specific exception and log, re-raise, or handle the failure explicitly.',
        sourceAnalyzer: 'python-project',
        ruleId: 'python/broad-except',
        confidence: 0.82,
        applicableProjectTypes: ['python'],
        tags: ['python', 'error-handling']
      }));
    }
  }
  return { analyzerId: 'python-project', findings };
}

export function javaAnalyzer(project: BrowserProject): AnalyzerResult {
  const javaFiles = project.files.filter((file) => file.path.endsWith('.java'));
  const hasJavaSignal = javaFiles.length > 0 || hasAny(project, ['pom.xml', 'build.gradle', 'build.gradle.kts']);
  if (!hasJavaSignal) {
    return { analyzerId: 'java-project', findings: [], skipped: true, skipReason: 'Not a Java project.' };
  }

  const findings: Finding[] = [];
  const hasGradle = hasAny(project, ['build.gradle', 'build.gradle.kts', 'settings.gradle', 'settings.gradle.kts']);
  if (javaFiles.length > 0 && !hasAny(project, ['pom.xml', 'build.gradle', 'build.gradle.kts'])) {
    findings.push(createFinding({
      title: 'Java build descriptor is missing',
      description: 'Java source files exist, but no Maven or Gradle build file was found.',
      severity: 'high',
      category: 'build',
      evidence: ['No pom.xml, build.gradle, or build.gradle.kts found.'],
      recommendation: 'Add a Maven or Gradle build descriptor so the project can be built consistently.',
      sourceAnalyzer: 'java-project',
      ruleId: 'java/build-descriptor-missing',
      confidence: 0.9,
      applicableProjectTypes: ['java'],
      tags: ['java', 'build']
    }));
  }
  if (hasGradle && !hasAny(project, ['gradlew', 'gradlew.bat'])) {
    findings.push(createFinding({
      title: 'Gradle wrapper is missing',
      description: 'The project uses Gradle but does not include the Gradle wrapper.',
      severity: 'low',
      category: 'build',
      evidence: ['Found Gradle build files without gradlew or gradlew.bat.'],
      recommendation: 'Commit the Gradle wrapper so contributors and CI use the same Gradle version.',
      sourceAnalyzer: 'java-project',
      ruleId: 'java/gradle-wrapper-missing',
      confidence: 0.74,
      applicableProjectTypes: ['java'],
      tags: ['java', 'gradle']
    }));
  }
  const hasTests = project.files.some((file) => file.path.startsWith('src/test/') || /Test\.java$/.test(file.path) || /Tests\.java$/.test(file.path));
  if (javaFiles.length > 0 && !hasTests) {
    findings.push(createFinding({
      title: 'Java tests are not visible',
      description: 'No conventional Java test sources were found.',
      severity: 'medium',
      category: 'test',
      evidence: ['No src/test directory or *Test.java files found.'],
      recommendation: 'Add unit or integration tests under src/test/java and wire them into Maven or Gradle.',
      sourceAnalyzer: 'java-project',
      ruleId: 'java/test-signal-missing',
      confidence: 0.8,
      applicableProjectTypes: ['java'],
      tags: ['java', 'test']
    }));
  }
  for (const file of javaFiles) {
    const emptyCatch = file.content.match(/catch\s*\([^)]*\)\s*\{\s*\}/m);
    if (emptyCatch?.index !== undefined) {
      const info = lineInfo(file.content, emptyCatch.index);
      findings.push(createFinding({
        title: 'Empty Java catch block',
        description: 'An exception is caught and ignored.',
        severity: 'high',
        category: 'bug',
        filePath: file.path,
        startLine: info.line,
        endLine: info.line,
        codeSnippet: info.snippet,
        evidence: ['Found an empty catch block.'],
        recommendation: 'Log, rethrow, or handle the exception explicitly.',
        sourceAnalyzer: 'java-project',
        ruleId: 'java/empty-catch',
        confidence: 0.88,
        applicableProjectTypes: ['java'],
        tags: ['java', 'error-handling']
      }));
    }
  }
  return { analyzerId: 'java-project', findings };
}

export function cppAnalyzer(project: BrowserProject): AnalyzerResult {
  const cppFiles = project.files.filter((file) => ['.c', '.cc', '.cpp', '.cxx', '.h', '.hh', '.hpp', '.hxx'].some((extension) => file.path.endsWith(extension)));
  const hasCppSignal = cppFiles.length > 0 || hasAny(project, ['CMakeLists.txt', 'Makefile', 'makefile', 'conanfile.txt', 'conanfile.py', 'vcpkg.json']);
  if (!hasCppSignal) {
    return { analyzerId: 'cpp-project', findings: [], skipped: true, skipReason: 'Not a C/C++ project.' };
  }

  const findings: Finding[] = [];
  if (cppFiles.length > 0 && !hasAny(project, ['CMakeLists.txt', 'Makefile', 'makefile', 'conanfile.txt', 'conanfile.py', 'vcpkg.json'])) {
    findings.push(createFinding({
      title: 'C/C++ build descriptor is missing',
      description: 'C/C++ source files exist, but no common build descriptor was found.',
      severity: 'high',
      category: 'build',
      evidence: ['No CMakeLists.txt, Makefile, conanfile, or vcpkg.json found.'],
      recommendation: 'Add CMake, Make, Conan, or vcpkg metadata so the project can be built reproducibly.',
      sourceAnalyzer: 'cpp-project',
      ruleId: 'cpp/build-descriptor-missing',
      confidence: 0.86,
      applicableProjectTypes: ['cpp'],
      tags: ['cpp', 'build']
    }));
  }
  const cmake = project.byPath['CMakeLists.txt'];
  if (cmake && !/cmake_minimum_required\s*\(/i.test(cmake.content)) {
    findings.push(createFinding({
      title: 'CMake minimum version is not declared',
      description: 'CMake projects should declare the minimum required CMake version.',
      severity: 'medium',
      category: 'build',
      filePath: 'CMakeLists.txt',
      evidence: ['CMakeLists.txt does not contain cmake_minimum_required(...).'],
      recommendation: 'Add cmake_minimum_required(VERSION ...) near the top of CMakeLists.txt.',
      sourceAnalyzer: 'cpp-project',
      ruleId: 'cpp/cmake-minimum-missing',
      confidence: 0.82,
      applicableProjectTypes: ['cpp'],
      tags: ['cpp', 'cmake']
    }));
  }
  if (cppFiles.length > 0 && !hasAny(project, ['.clang-format', '_clang-format'])) {
    findings.push(createFinding({
      title: 'C/C++ formatting policy is missing',
      description: 'No clang-format configuration was found.',
      severity: 'low',
      category: 'maintainability',
      evidence: ['No .clang-format or _clang-format file found.'],
      recommendation: 'Add a clang-format configuration to keep C/C++ diffs consistent.',
      sourceAnalyzer: 'cpp-project',
      ruleId: 'cpp/clang-format-missing',
      confidence: 0.7,
      applicableProjectTypes: ['cpp'],
      tags: ['cpp', 'style']
    }));
  }
  const hasTests = project.files.some((file) => /(^|\/)(tests?|spec)\//i.test(file.path) || /(_test|Test)\.(c|cc|cpp|cxx)$/.test(file.path));
  if (cppFiles.length > 0 && !hasTests) {
    findings.push(createFinding({
      title: 'C/C++ tests are not visible',
      description: 'No conventional C/C++ test directory or test source file was found.',
      severity: 'medium',
      category: 'test',
      evidence: ['No tests/, test/, *_test.cpp, or *Test.cpp files found.'],
      recommendation: 'Add a lightweight test target and wire it into CTest, Make, or CI.',
      sourceAnalyzer: 'cpp-project',
      ruleId: 'cpp/test-signal-missing',
      confidence: 0.76,
      applicableProjectTypes: ['cpp'],
      tags: ['cpp', 'test']
    }));
  }
  for (const file of cppFiles) {
    const unsafe = file.content.match(/\b(gets|strcpy|strcat|sprintf)\s*\(/m);
    if (unsafe?.index !== undefined) {
      const info = lineInfo(file.content, unsafe.index);
      findings.push(createFinding({
        title: 'Unsafe C/C++ API usage',
        description: 'The source uses a C API that is commonly associated with buffer overflows.',
        severity: 'high',
        category: 'bug',
        filePath: file.path,
        startLine: info.line,
        endLine: info.line,
        codeSnippet: info.snippet,
        evidence: [`Matched ${unsafe[1]}(...).`],
        recommendation: 'Use bounded alternatives and validate buffer sizes; enable compiler warnings and sanitizers.',
        sourceAnalyzer: 'cpp-project',
        ruleId: 'cpp/unsafe-c-api',
        confidence: 0.84,
        applicableProjectTypes: ['cpp'],
        tags: ['cpp', 'memory-safety'],
        fixComplexity: 'medium'
      }));
    }
  }
  return { analyzerId: 'cpp-project', findings };
}
