import { existsSync } from 'node:fs';
import { join } from 'node:path';
import type { Analyzer, Finding } from '@codedoctor/shared';
import { finding, hasProjectType, readTextFile } from './utils.js';

function firstScriptTarget(command: string): string | null {
  const match = command.match(/\b(?:node|tsx|ts-node)\s+([^\s]+)/);
  return match?.[1] ?? null;
}

export const nodeDependencyAnalyzer: Analyzer = {
  id: 'node-dependency',
  name: 'Node Dependency Analyzer',
  capability: {
    languages: ['javascript', 'typescript'],
    frameworks: ['any'],
    projectTypes: ['node-web'],
    filePatterns: ['package.json', '*lock.yaml', 'package-lock.json', 'yarn.lock'],
    categories: ['dependency', 'build', 'config'],
    confidence: 'high',
    requiresExternalTool: false,
    requiresNetwork: false,
    requiresAI: false,
    optional: false
  },
  canRun: (context) => hasProjectType(context, 'node-web'),
  async analyze(context) {
    const findings: Finding[] = [];
    const packageFile = context.files.byPath['package.json'];
    if (!packageFile) {
      return { analyzerId: 'node-dependency', findings };
    }

    const content = await readTextFile(packageFile);
    const pkg = content ? JSON.parse(content) as { scripts?: Record<string, string>; dependencies?: Record<string, string>; devDependencies?: Record<string, string> } : {};
    const scripts = pkg.scripts ?? {};
    if (!scripts.build && !scripts.start && !scripts.dev) {
      findings.push(
        finding({
          title: 'No runnable package script',
          description: 'package.json does not define dev, start, or build scripts, so users may not know how to run the project.',
          severity: 'medium',
          category: 'build',
          filePath: 'package.json',
          evidence: ['Missing scripts.dev, scripts.start, and scripts.build.'],
          recommendation: 'Add explicit dev/start/build scripts that match the actual project entry points.',
          sourceAnalyzer: 'node-dependency',
          ruleId: 'node/no-runnable-script',
          confidence: 0.9,
          tags: ['package-json', 'scripts']
        })
      );
    }

    for (const [name, command] of Object.entries(scripts)) {
      const target = firstScriptTarget(command);
      if (!target) {
        continue;
      }
      const normalized = target.replace(/^\.\//, '');
      if (!existsSync(join(context.rootPath, normalized))) {
        findings.push(
          finding({
            title: 'Package script target is missing',
            description: 'A package.json script points to a file that does not exist.',
            severity: 'high',
            category: 'build',
            filePath: 'package.json',
            evidence: [`scripts.${name} runs "${command}", but ${normalized} was not found.`],
            recommendation: 'Create the referenced entry file or update the script to match the real entry point.',
            sourceAnalyzer: 'node-dependency',
            ruleId: 'node/script-target-missing',
            confidence: 0.95,
            tags: ['package-json', 'scripts']
          })
        );
      }
    }

    const hasLockfile = ['pnpm-lock.yaml', 'package-lock.json', 'yarn.lock'].some((path) => context.files.byPath[path]);
    if (!hasLockfile) {
      findings.push(
        finding({
          title: 'Missing Node lockfile',
          description: 'The project has package.json but no package manager lockfile, making installs less reproducible.',
          severity: 'medium',
          category: 'dependency',
          filePath: 'package.json',
          evidence: ['No pnpm-lock.yaml, package-lock.json, or yarn.lock found.'],
          recommendation: 'Commit the lockfile generated by the package manager used for the project.',
          sourceAnalyzer: 'node-dependency',
          ruleId: 'node/missing-lockfile',
          confidence: 0.86,
          tags: ['dependencies', 'lockfile']
        })
      );
    }

    const envReferenced = context.files.files.some((file) => file.path.endsWith('.ts') || file.path.endsWith('.tsx') || file.path.endsWith('.js') || file.path.endsWith('.jsx'));
    if (envReferenced && !context.files.byPath['.env.example']) {
      findings.push(
        finding({
          title: 'Missing .env.example',
          description: 'The project appears to use application code but does not document required environment variables.',
          severity: 'low',
          category: 'config',
          evidence: ['No .env.example file found.'],
          recommendation: 'Add .env.example with required variable names and safe example values.',
          sourceAnalyzer: 'node-dependency',
          ruleId: 'node/env-example-missing',
          confidence: 0.55,
          tags: ['environment']
        })
      );
    }

    return { analyzerId: 'node-dependency', findings };
  }
};
