import type { Analyzer, AnalyzerResult, Finding } from '@codedoctor/shared';
import { finding, hasProjectType, lineInfo, readTextFile } from './utils.js';

const dependencyFiles = ['pyproject.toml', 'requirements.txt', 'Pipfile'];
const lockFiles = ['uv.lock', 'poetry.lock', 'Pipfile.lock', 'requirements.lock'];
const entryFiles = ['main.py', 'app.py', 'manage.py'];

function hasFile(context: Parameters<Analyzer['canRun']>[0], path: string): boolean {
  return Boolean(context.files.byPath[path]);
}

function hasAnyFile(context: Parameters<Analyzer['canRun']>[0], paths: string[]): boolean {
  return paths.some((path) => hasFile(context, path));
}

export const pythonProjectAnalyzer: Analyzer = {
  id: 'python-project',
  name: 'Python Project Analyzer',
  capability: {
    languages: ['python'],
    frameworks: ['django', 'fastapi', 'unknown'],
    projectTypes: ['python'],
    filePatterns: ['*.py', 'pyproject.toml', 'requirements.txt', 'uv.lock', 'poetry.lock'],
    categories: ['dependency', 'build', 'test', 'bug', 'maintainability', 'config'],
    confidence: 'medium',
    requiresExternalTool: false,
    requiresNetwork: false,
    requiresAI: false,
    optional: false
  },
  canRun: (context) => hasProjectType(context, 'python'),
  async analyze(context): Promise<AnalyzerResult> {
    const findings: Finding[] = [];
    const pythonFiles = context.files.files.filter((file) => file.path.endsWith('.py'));

    if (!hasAnyFile(context, dependencyFiles)) {
      findings.push(finding({
        title: 'Python dependency manifest is missing',
        description: 'Python source exists, but no pyproject.toml, requirements.txt, or Pipfile was found.',
        severity: 'medium',
        category: 'dependency',
        evidence: ['No standard Python dependency manifest found at the project root.'],
        recommendation: 'Add pyproject.toml or requirements.txt so the runtime dependencies are reproducible.',
        sourceAnalyzer: 'python-project',
        ruleId: 'python/dependency-manifest-missing',
        confidence: 0.84,
        applicableProjectTypes: ['python'],
        tags: ['python', 'dependency']
      }));
    }

    if (hasAnyFile(context, ['pyproject.toml', 'Pipfile']) && !hasAnyFile(context, lockFiles)) {
      findings.push(finding({
        title: 'Python lockfile is missing',
        description: 'The project uses a modern Python dependency manifest but has no lockfile.',
        severity: 'low',
        category: 'dependency',
        evidence: ['Found pyproject.toml or Pipfile without uv.lock, poetry.lock, or Pipfile.lock.'],
        recommendation: 'Commit the lockfile generated by uv, Poetry, or Pipenv when the project expects reproducible installs.',
        sourceAnalyzer: 'python-project',
        ruleId: 'python/lockfile-missing',
        confidence: 0.72,
        applicableProjectTypes: ['python'],
        tags: ['python', 'dependency']
      }));
    }

    const hasTests = context.files.files.some((file) => /^tests?\//.test(file.path) || /(^|\/)test_.*\.py$/.test(file.path) || /_test\.py$/.test(file.path));
    if (pythonFiles.length > 0 && !hasTests) {
      findings.push(finding({
        title: 'Python tests are not visible',
        description: 'No pytest/unittest-style test files or tests directory were found.',
        severity: 'medium',
        category: 'test',
        evidence: ['No tests/, test_*.py, or *_test.py files found.'],
        recommendation: 'Add a small tests/ suite and document the test command.',
        sourceAnalyzer: 'python-project',
        ruleId: 'python/test-signal-missing',
        confidence: 0.78,
        applicableProjectTypes: ['python'],
        tags: ['python', 'test']
      }));
    }

    if (!hasAnyFile(context, entryFiles) && !hasFile(context, 'pyproject.toml')) {
      findings.push(finding({
        title: 'Python entry point is unclear',
        description: 'The project has Python files but no common entry file or pyproject metadata.',
        severity: 'info',
        category: 'build',
        evidence: ['No main.py, app.py, manage.py, or pyproject.toml found.'],
        recommendation: 'Document the runtime entry point in README or pyproject scripts.',
        sourceAnalyzer: 'python-project',
        ruleId: 'python/entrypoint-unclear',
        confidence: 0.58,
        applicableProjectTypes: ['python'],
        tags: ['python', 'build']
      }));
    }

    for (const file of pythonFiles) {
      const content = await readTextFile(file);
      if (!content) {
        continue;
      }
      const broadExcept = content.match(/except\s+(Exception|BaseException)?\s*:\s*(pass)?/m);
      if (broadExcept?.index !== undefined) {
        const info = lineInfo(content, broadExcept.index);
        findings.push(finding({
          title: 'Broad or empty Python exception handling',
          description: 'A broad except block can hide runtime failures and make debugging harder.',
          severity: broadExcept[2] ? 'high' : 'medium',
          category: 'bug',
          filePath: file.path,
          startLine: info.line,
          endLine: info.line,
          codeSnippet: info.snippet,
          evidence: ['Matched a broad except block.'],
          recommendation: 'Catch a specific exception and log, re-raise, or handle the failure explicitly.',
          sourceAnalyzer: 'python-project',
          ruleId: 'python/broad-except',
          confidence: 0.82,
          applicableProjectTypes: ['python'],
          tags: ['python', 'error-handling']
        }));
      }
    }

    return { analyzerId: 'python-project', findings };
  }
};
